language: ruby
rvm:
- 2.5.1
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: EA5k9S0p4i9kXcNsZNDqHAih0PiLRK8rM0IR6KAbRDSEEs9zSJBUtPW1OKMb/58BEcTm4atIQwZYXMe8ssU1n2S0N6jMkKeSRVK5QzNKksHwxOHIZYtLuO995Cuxy6YBRNSTrbgTBZMMtM3RN1oBNcOKf/MmRu+kw1HHz8yHcfHpWFnMIOGHhEFCpEeH/D8x6JV+TcdeeGCls5iSXahro8iYboRhicni31szaAz/57cOG9/oLizjFPPv0F5m0LoSQeRS6WT2TOIiFkHzf8E3waYJatiWsNKPGtHcEBQw7aMyJ7SU6FzJeWf2BxilMWUc22uLKAk4QqzgrQf2vOgO8hwZGav8we2/B5o2NQE0o+bYzHHFwT4RhyVoDdHE3bS3/q8ikoyyvWDiTSeUMfk5sPExb4V5zr8iy7uZn9MiCjWZUb4g+T2gqdMYXi+apAJb14oLz9E46dT2lFp6DeINgEVBlkUUAwzF91L836iu8cgAqtdjLYSoATYv+tkRfSdPIxkppyHG+XgNgLieRije1Ze/VpSmBiLc1ncX6V5Kl7Zbugtt3Zndd4Q7HW1L9wD032Od2nAV41eFtNKrl2x4QM4c+m+URNWYpKRFaadSoMdkkOPHQoAC1udzqPp8tsI16DvyU7I+0XPc4OwU9KmJ/CUS12PRBYSjxFvau4TGbCU=
  run: "rake db:migrate"
